spring.application.name=AuthServiceQuickBite

server.port=8081

spring.datasource.url=jdbc:mysql://localhost:3306/quickbite_auth?createDatabaseIfNotExist=true

spring.datasource.username=root
spring.datasource.password=admin

spring.jpa.hibernate.ddl-auto=none

spring.jpa.show-sql=true

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration